Repository deckhouse/virtualization, pull requests merged in 2024-10, with the labels that each got.

#425 chore(vmclass): add backup label
  api/core/v1alpha2/virtual_machine_class.go
  crds/virtualmachineclasses.yaml
Labels: validation/skip/doc_changes

#396 chore(main): release 0.14.0
  CHANGELOG.md
Labels: autorelease: pending

#452 refactor(lint): add helm templates validation
  .github/workflows/dev_validation.yaml
  Taskfile.yaml
  tools/kubeconform/.gitignore
  tools/kubeconform/fixtures/module-values.yaml
  tools/kubeconform/kubeconform.sh
Labels: validation/skip/helm_templates

#455 chore(ci): build from source registry2
  images/dvcr/werf.inc.yaml
Labels: validation/skip/helm_templates

#468 feat(vmclass): immutable .spec.cpu
  api/core/v1alpha2/virtual_machine_class.go
  crds/virtualmachineclasses.yaml
Labels: validation/skip/doc_changes
