Repository deckhouse/virtualization, pull requests merged in 2025-05, with the labels that each got.

#890 feat(vm): live migration policies
  api/core/v1alpha2/virtual_machine.go
  api/core/v1alpha2/virtual_machine_operation.go
  api/core/v1alpha2/vmopcondition/condition.go
  api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go
  crds/doc-ru-virtualmachineoperations.yaml
  crds/doc-ru-virtualmachines.yaml
  crds/virtualmachineoperations.yaml
  crds/virtualmachines.yaml
  images/virt-artifact/patches/034-allow-update-kvvmi-for-virtualization-sas.patch
  images/virt-artifact/patches/051-set-migration-configuration-externally.patch
  images/virt-artifact/patches/README.md
  images/virtualization-artifact/cmd/virtualization-controller/main.go
  images/virtualization-artifact/pkg/builder/vmop/option.go
  images/virtualization-artifact/pkg/builder/vmop/vmop.go
  images/virtualization-artifact/pkg/config/load_live_migration_settings.go
  images/virtualization-artifact/pkg/controller/livemigration/internal/dynamic_settings_handler.go
  images/virtualization-artifact/pkg/controller/livemigration/internal/dynamic_settings_handler_test.go
  images/virtualization-artifact/pkg/controller/livemigration/internal/suite_test.go
  images/virtualization-artifact/pkg/controller/livemigration/internal/watcher/kvvmi.go
  images/virtualization-artifact/pkg/controller/livemigration/internal/watcher/kvvmim.go
  images/virtualization-artifact/pkg/controller/livemigration/live_migration_controller.go
  images/virtualization-artifact/pkg/controller/livemigration/live_migration_reconciler.go
  images/virtualization-artifact/pkg/controller/powerstate/operations.go
  images/virtualization-artifact/pkg/controller/vmop/internal/deletion_test.go
  images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go
  images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle_test.go
  images/virtualization-artifact/pkg/livemigration/migration_configuration.go
  images/virtualization-artifact/pkg/livemigration/policy.go
  templates/kubevirt/kubevirt.yaml
  templates/virtualization-controller/_helpers.tpl
  tests/e2e/testdata/vm-migration/vm/overlays/migration-always-forced/kustomization.yaml
  tests/e2e/testdata/vm-migration/vm/overlays/migration-always-forced/vd.image.patch.yaml
  tests/e2e/testdata/vm-migration/vm/overlays/migration-always-safe/kustomization.yaml
  tests/e2e/testdata/vm-migration/vm/overlays/migration-always-safe/vd.image.patch.yaml
  tests/e2e/testdata/vm-migration/vm/overlays/migration-prefer-forced/kustomization.yaml
  tests/e2e/testdata/vm-migration/vm/overlays/migration-prefer-forced/vd.image.patch.yaml
  tests/e2e/testdata/vm-migration/vm/overlays/migration-prefer-safe/kustomization.yaml
  tests/e2e/testdata/vm-migration/vm/overlays/migration-prefer-safe/vd.image.patch.yaml
Labels: e2e/user/danilrwx

#1027 Backport: fix(module): update deckhouse requirements
  module.yaml
Labels: auto, backported

#1025 Changelog v0.17.1
  CHANGELOG/CHANGELOG-v0.17.1.yml
  CHANGELOG/CHANGELOG-v0.17.md
Labels: changelog, auto, status/backport

#1028 Backport: Changelog v0.17.1
  CHANGELOG/CHANGELOG-v0.17.1.yml
  CHANGELOG/CHANGELOG-v0.17.md
Labels: auto, backported

#1030 Backport: docs: update docs due v0.18.0
  docs/ADMIN_GUIDE.md
  docs/ADMIN_GUIDE.ru.md
  docs/INSTALL.md
  docs/INSTALL.ru.md
  docs/USER_GUIDE.md
  docs/USER_GUIDE.ru.md
  docs/images/vm-corefraction.drawio
Labels: auto, backported

#1031 Backport: feat(module): add vm livemigration stat dashboard
  monitoring/grafana-dashboards/main/virtual-machine.json
  templates/kubevirt/service-monitor.yaml
Labels: auto, backported

#1035 Changelog v0.17.1
  CHANGELOG/CHANGELOG-v0.17.1.yml
Labels: changelog, auto, status/backport

#1036 Backport: Changelog v0.17.1
  CHANGELOG/CHANGELOG-v0.17.1.yml
Labels: auto, backported

#1037 Changelog v0.17.1
  CHANGELOG/CHANGELOG-v0.17.1.yml
Labels: changelog, auto, status/backport

#1038 Backport: Changelog v0.17.1
  CHANGELOG/CHANGELOG-v0.17.1.yml
Labels: auto, backported

#1047 Backport: fix(vm): fix live migration with image hotplug
  images/virtualization-artifact/pkg/controller/livemigration/live_migration_reconciler.go
  images/virtualization-artifact/pkg/livemigration/migration_configuration.go
Labels: auto, backported

#1049 chore(module): remove png builder script from module image
  werf.yaml
Labels: e2e/user/fl64

#831 Changelog v0.18.0
  CHANGELOG/CHANGELOG-v0.18.0.yml
  CHANGELOG/CHANGELOG-v0.18.md
Labels: changelog, auto, status/backport

#1051 Backport: Changelog v0.18.0
  CHANGELOG/CHANGELOG-v0.18.0.yml
  CHANGELOG/CHANGELOG-v0.18.md
Labels: auto, backported

#1039 chore(module): fix CVEs
  .github/workflows/dev_module_build.yml
  base-images/virtualization_images.yml
  images/base-alt-p10/werf.inc.yaml
  images/bounder/werf.inc.yaml
  images/cdi-artifact/werf.inc.yaml
  images/cdi-cloner/werf.inc.yaml
  images/dvcr-artifact/go.mod
  images/dvcr-artifact/go.sum
  images/dvcr-artifact/werf.inc.yaml
  images/dvcr/werf.inc.yaml
  images/hooks/go.mod
  images/hooks/go.sum
  images/kube-api-rewriter/go.mod
  images/kube-api-rewriter/go.sum
  images/kube-api-rewriter/werf.inc.yaml
  images/pre-delete-hook/go.mod
  images/pre-delete-hook/go.sum
  images/pre-delete-hook/werf.inc.yaml
  images/virt-artifact/werf.inc.yaml
  images/virt-launcher/vlctl/go.mod
  images/virt-launcher/vlctl/go.sum
  images/virt-launcher/werf.inc.yaml
  images/virtualization-artifact/go.mod
  images/virtualization-artifact/go.sum
  images/virtualization-artifact/werf.inc.yaml
  images/vm-route-forge/go.mod
  images/vm-route-forge/go.sum
  images/vm-route-forge/werf.inc.yaml
  templates/dvcr/deployment.yaml
  werf.yaml
Labels: e2e/user/danilrwx

#1071 Backport: fix(vm): fix condition based metrics
  images/virtualization-artifact/pkg/monitoring/metrics/virtualmachine/data_metric.go
Labels: auto, backported

#1070 Changelog v0.18.1
  CHANGELOG/CHANGELOG-v0.18.1.yml
  CHANGELOG/CHANGELOG-v0.18.md
Labels: changelog, auto, status/backport

#1074 Backport: Changelog v0.18.1
  CHANGELOG/CHANGELOG-v0.18.1.yml
  CHANGELOG/CHANGELOG-v0.18.md
Labels: auto, backported

#1077 Backport: fix(ci): fix variable for module tag
  .github/workflows/dev_module_build.yml
  .github/workflows/release_module_build-and-registration.yml
  .github/workflows/release_module_release-channels.yml
Labels: auto, backported

#1083 fix(vm): set max embedded cloud-init block size
  crds/virtualmachines.yaml
Labels: validation/skip/doc_changes

#1068 docs: update docs due v0.19.0
  docs/ADMIN_GUIDE.md
  docs/FAQ.md
  docs/FAQ.ru.md
  docs/USER_GUIDE.md
  docs/USER_GUIDE.ru.md
  docs/images/vm-corefraction.drawio
  docs/images/vm-corefraction.png
  docs/images/vm-corefraction.ru.png
Labels: documentation, validation/skip/doc_changes

#1026 Changelog v0.19.0
  CHANGELOG/CHANGELOG-v0.19.0.yml
  CHANGELOG/CHANGELOG-v0.19.md
Labels: changelog, auto, status/backport

#1106 Backport: Changelog v0.19.0
  CHANGELOG/CHANGELOG-v0.19.0.yml
  CHANGELOG/CHANGELOG-v0.19.md
Labels: auto, backported

#1098 Changelog v0.18.2
  CHANGELOG/CHANGELOG-v0.18.2.yml
  CHANGELOG/CHANGELOG-v0.18.md
Labels: changelog, auto, status/backport

#1103 chore(module): mitigate CVEs in Python parts, remove unused code
  hooks/lib/certificate/__init__.py
  hooks/lib/certificate/certificate.py
  hooks/lib/certificate/parse.py
  hooks/lib/hooks/internal_tls.py
  hooks/lib/password_generator/__init__.py
  hooks/lib/password_generator/htpasswd.py
  hooks/lib/password_generator/password_generator.py
  hooks/lib/tests/test_internal_tls_test.py
  lib/python/requirements.txt
  werf.yaml
Labels: skip/e2e
