Repository deckhouse/virtualization, pull requests merged in 2025-07, with the labels that each got.

#1221 Changelog v0.21.1
  CHANGELOG/CHANGELOG-v0.21.1.yml
  CHANGELOG/CHANGELOG-v0.21.md
Labels: changelog, auto, status/backport

#1227 Backport: Changelog v0.21.1
  CHANGELOG/CHANGELOG-v0.21.1.yml
  CHANGELOG/CHANGELOG-v0.21.md
Labels: auto, backported

#1235 Changelog v0.20.2
  CHANGELOG/CHANGELOG-v0.20.2.yml
  CHANGELOG/CHANGELOG-v0.20.md
Labels: changelog, auto, status/backport

#1230 chore(vmbda): add columns with blockdevice kind and name for wide output
  api/core/v1alpha2/virtual_machine_block_device_attachment.go
  crds/virtualmachineblockdeviceattachments.yaml
Labels: validation/skip/doc_changes

#1242 Backport: Changelog v0.21.2
  CHANGELOG/CHANGELOG-v0.21.2.yml
  CHANGELOG/CHANGELOG-v0.21.md
Labels: auto, backported

#1214 chore(core): integrate self-build libs
  .werf/defines/images.tmpl
  component_versions/version_map.yml
  images/base-alt-p11-binaries/werf.inc.yaml
  images/dvcr-artifact/werf.inc.yaml
  images/edk2/werf.inc.yaml
  images/libvirt/werf.inc.yaml
  images/packages/binaries/acl/werf.inc.yaml
  images/packages/binaries/dmidecode/README.md
  images/packages/binaries/dmidecode/werf.inc.yaml
  images/packages/binaries/file/README.md
  images/packages/binaries/gnutls/README.md
  images/packages/binaries/gnutls/werf.inc.yaml
  images/packages/binaries/libattr/README.md
  images/packages/binaries/libaudit/README.md
  images/packages/binaries/libblkid/README.md
  images/packages/binaries/libblkid/werf.inc.yaml
  images/packages/binaries/libbrotli/README.md
  images/packages/binaries/libbsd/README.md
  images/packages/binaries/libburn/README.md
  images/packages/binaries/libfuse3/README.md
  images/packages/binaries/libfuse3/werf.inc.yaml
  images/packages/binaries/libgcrypt/README.md
  images/packages/binaries/libgcrypt/werf.inc.yaml
  images/packages/binaries/libgmp/README.md
  images/packages/binaries/libgmp/werf.inc.yaml
  images/packages/binaries/libgsasl/werf.inc.yaml
  images/packages/binaries/libidn/README.md
  images/packages/binaries/libidn/werf.inc.yaml
  images/packages/binaries/libidn2/README.md
  images/packages/binaries/libidn2/werf.inc.yaml
  images/packages/binaries/libisoburn/README.md
  images/packages/binaries/libisoburn/werf.inc.yaml
  images/packages/binaries/libmd/README.md
  images/packages/binaries/libmd/werf.inc.yaml
  images/packages/binaries/lvm2/werf.inc.yaml
  images/packages/binaries/nbdkit/README.md
  images/packages/binaries/nbdkit/werf.inc.yaml
  images/packages/binaries/nettle/README.md
  images/packages/binaries/nettle/werf.inc.yaml
  images/packages/binaries/nftables/README.md
  images/packages/binaries/nftables/werf.inc.yaml
  images/packages/binaries/numactl/README.md
  images/packages/binaries/openssl/README.md
  images/packages/binaries/swtpm/README.md
  images/packages/binaries/swtpm/werf.inc.yaml
  images/qemu/werf.inc.yaml
  images/virt-artifact/werf.inc.yaml
  images/virt-handler/werf.inc.yaml
  images/virt-launcher/werf.inc.yaml
Labels: e2e/user/nevermarine

#1190 Changelog v0.22.0
  CHANGELOG/CHANGELOG-v0.22.0.yml
  CHANGELOG/CHANGELOG-v0.22.md
Labels: changelog, auto, status/backport

#1249 Backport: Changelog v0.22.0
  CHANGELOG/CHANGELOG-v0.22.0.yml
  CHANGELOG/CHANGELOG-v0.22.md
Labels: auto, backported

#1048 fix(ci): fix run e2e if audit disabled
  tests/e2e/Taskfile.yaml
Labels: e2e/user/loktev-d

#1280 Backport: docs: update due v0.23.0
  docs/USER_GUIDE.md
  docs/USER_GUIDE.ru.md
Labels: auto, backported

#1238 Changelog v0.23.0
  CHANGELOG/CHANGELOG-v0.23.0.yml
  CHANGELOG/CHANGELOG-v0.23.md
Labels: changelog, auto, status/backport

#1282 chore(ci): drop transient image base-alt-p11, use builder/alt directly
  images/base-alt-p11/werf.inc.yaml
  images/edk2/werf.inc.yaml
  images/libvirt/werf.inc.yaml
  images/qemu/werf.inc.yaml
  images/virt-artifact/werf.inc.yaml
Labels: validation/skip/doc_changes, validation/skip/copyright

#1283 fix(hooks): fix backported commit PR 1269
  images/hooks/cmd/tls-certificates-audit/main.go
  images/hooks/pkg/hooks/tls-certificates-audit/hook.go
Labels: validation/skip/doc_changes
