Repository deckhouse/virtualization, pull requests merged in 2025-02, with the labels that each got.

#677 docs: fix alert in virtualMachineCIDRs parameter
  openapi/config-values.yaml
  openapi/doc-ru-config-values.yaml
Labels: documentation

#588 chore(core): build libvirt,qemu,edk2
  cv/README.md
  cv/version_map.yml
  images/edk2/build.sh
  images/edk2/json/40-edk2-ovmf-x64-sb.json
  images/edk2/json/50-edk2-ovmf-x64-nosb.json
  images/edk2/json/60-edk2-ovmf-x64-amdsev.json
  images/edk2/json/60-edk2-ovmf-x64-inteltdx.json
  images/edk2/logo/Logo.bmp
  images/edk2/logo/README.md
  images/edk2/logo/bmp-info.py
  images/edk2/uefi-revocation-list/DBXUpdate-20230509.x64.bin
  images/edk2/werf.inc.yaml
  images/libvirt/install-libvirt.sh
  images/libvirt/werf.inc.yaml
  images/qemu/install-qemu.sh
  images/qemu/werf.inc.yaml
  images/virt-artifact/werf.inc.yaml
  images/virt-launcher/libvirt.conf
  images/virt-launcher/reloclibs.sh
  images/virt-launcher/werf.inc.yaml
  werf.yaml
Labels: build/github/ubuntu

#675 feat(api): create NetworkPolicy for Importer pod
  images/virtualization-artifact/pkg/common/annotations/annotations.go
  images/virtualization-artifact/pkg/common/network_policy/network_policy.go
  images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go
  images/virtualization-artifact/pkg/controller/importer/importer_pod.go
  images/virtualization-artifact/pkg/controller/service/disk_service.go
  images/virtualization-artifact/pkg/controller/service/importer_service.go
  images/virtualization-artifact/pkg/controller/vd/vd_controller.go
  images/virtualization-artifact/pkg/controller/vi/vi_controller.go
  templates/virtualization-controller/rbac-for-us.yaml
  tests/e2e/config/config.go
  tests/e2e/config/project.go
  tests/e2e/default_config.yaml
  tests/e2e/importer_network_policy_test.go
  tests/e2e/kubectl/resource.go
  tests/e2e/testdata/importer-network-policy/base/cvi.yaml
  tests/e2e/testdata/importer-network-policy/base/kustomization.yaml
  tests/e2e/testdata/importer-network-policy/base/vd.yaml
  tests/e2e/testdata/importer-network-policy/base/vi.yaml
  tests/e2e/testdata/importer-network-policy/base/vm.yaml
  tests/e2e/testdata/importer-network-policy/kustomization.yaml
  tests/e2e/testdata/importer-network-policy/project/kustomization.yaml
  tests/e2e/testdata/importer-network-policy/project/project.yaml
  tests/e2e/testdata/importer-network-policy/transformer.yaml
  tests/e2e/tests_suite_test.go
  tests/e2e/util_test.go
Labels: build/github/ubuntu

#728 Backport: chore(ci): add dev release build
  .github/workflows/dev_module_build.yml
  werf_cleanup.yaml
Labels: auto, backported

#681 feat(vm): add hotplug images to `VirtualMachine` status
  images/virtualization-artifact/pkg/controller/vm/internal/block_device.go
  images/virtualization-artifact/pkg/controller/vm/internal/block_devices_test.go
  images/virtualization-artifact/pkg/controller/vm/internal/state/state.go
Labels: build/github/ubuntu

#729 chore(ci): fix release branch build
  .github/workflows/dev_module_build.yml
Labels: status/backport

#734 Backport: chore(ci): fix release branch build
  .github/workflows/dev_module_build.yml
Labels: auto, backported

#736 Backport: fix(vmbda): add serial for vi, cvi
  images/virtualization-artifact/pkg/controller/service/attachment_service.go
Labels: auto, backported

#739 Backport: fix(api): add validation for short block device names
  images/virtualization-artifact/pkg/common/blockdevice/block_device.go
  images/virtualization-artifact/pkg/controller/cvi/cvi_webhook.go
  images/virtualization-artifact/pkg/controller/vd/internal/validator/name_validator.go
  images/virtualization-artifact/pkg/controller/vi/vi_webhook.go
  tests/e2e/testdata/images-creation/cvi/cvi_objectref_cvi.yaml
  tests/e2e/testdata/images-creation/cvi/cvi_objectref_vd.yaml
  tests/e2e/testdata/images-creation/cvi/cvi_objectref_vdsnapshot.yaml
  tests/e2e/testdata/images-creation/cvi/cvi_objectref_vi.yaml
  tests/e2e/testdata/images-creation/vi/vi_objectref_cvi.yaml
  tests/e2e/testdata/images-creation/vi/vi_objectref_vd.yaml
  tests/e2e/testdata/images-creation/vi/vi_objectref_vdsnapshot.yaml
  tests/e2e/testdata/images-creation/vi/vi_objectref_vi.yaml
  tests/e2e/testdata/images-creation/vi/vi_pvc_objectref_vi.yaml
Labels: auto, backported

#740 Backport: docs: update requirements
  docs/INSTALL.md
  docs/INSTALL_RU.md
  docs/USER_GUIDE_RU.md
Labels: auto, backported

#676 Changelog v0.16.0
  CHANGELOG/CHANGELOG-v0.16.0.yml
  CHANGELOG/CHANGELOG-v0.16.md
Labels: changelog, auto, status/backport

#741 Backport: Changelog v0.16.0
  CHANGELOG/CHANGELOG-v0.16.0.yml
  CHANGELOG/CHANGELOG-v0.16.md
Labels: auto, backported

#678 fix(vm): fix VM restart behavior with invalid spec
  api/core/v1alpha2/events.go
  images/virtualization-artifact/pkg/common/annotations/annotations.go
  images/virtualization-artifact/pkg/common/kvvm/kvvm.go
  images/virtualization-artifact/pkg/controller/service/vm_operation.go
  images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go
  images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go
  images/virtualization-artifact/pkg/controller/vm/internal/util.go
  images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
  images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go
  images/virtualization-artifact/pkg/controller/vmop/internal/operation.go
Labels: build/github/ubuntu

#762 Backport: fix(core): add policies to rbac
  templates/kubevirt/virt-operator/rbac-for-us.yaml
Labels: auto, backported

#764 Backport: fix(vi): refactor vd-snapshot data source handler
  api/core/v1alpha2/vdscondition/condition.go
  api/core/v1alpha2/vicondition/condition.go
  api/core/v1alpha2/vmscondition/condition.go
  images/virtualization-artifact/pkg/common/blockdevice/runner.go
  images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vdsnapshot.go
  images/virtualization-artifact/pkg/controller/importer/importer_pod.go
  images/virtualization-artifact/pkg/controller/indexer/indexer.go
  images/virtualization-artifact/pkg/controller/indexer/vi_indexer.go
  images/virtualization-artifact/pkg/controller/service/bounder_service.go
  images/virtualization-artifact/pkg/controller/service/importer_service.go
  images/virtualization-artifact/pkg/controller/service/protection_service.go
  images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vdsnapshot.go
  images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vdsnapshot_test.go
  images/virtualization-artifact/pkg/controller/vi/internal/datasource_ready.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/interfaces.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/mock.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot_cr.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot_cr_test.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot_pvc.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot_pvc_test.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/step/create_bounder_pod_step.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/step/create_pod_step.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/step/create_pvc_step.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/step/ready_cr_step.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/step/ready_pvc_step.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/step/terminating_step.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/step/wait_for_pod_step.go
  images/virtualization-artifact/pkg/controller/vi/internal/source/step/wait_for_pvc_step.go
  images/virtualization-artifact/pkg/controller/vi/internal/watcher/pod_watcher.go
  images/virtualization-artifact/pkg/controller/vi/internal/watcher/vdsnapshot_watcher.go
  images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go
Labels: auto, backported

#765 Backport: fix(vi): add watcher for vm to reconcile protection finalizers
  images/virtualization-artifact/pkg/controller/vi/internal/watcher/vm_watcher.go
  images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go
Labels: auto, backported

#766 Backport: fix(vmop): resolve resource hang in 'InProgress' state for Evict/Migrate
  images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go
  images/virtualization-artifact/pkg/controller/vmop/vmop_reconciler.go
Labels: auto, backported

#769 Backport: chore(ci): fix var module_edition for deploy for dev
  .github/workflows/dev_module_build-and-registration.yml
Labels: auto, backported

#777 Backport: fix(vi): add watcher for virtv2 virtual machines
  images/virtualization-artifact/pkg/controller/vi/internal/watcher/vm_watcher.go
Labels: auto, backported

#779 Backport: fix(vdsnapshot): set volume snapshot name to status
  images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle.go
  images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go
Labels: auto, backported
