Repository deckhouse/virtualization, pull requests merged in 2025-03, with the labels that each got.

#835 docs: fix links of virtual machine images at user guide
  docs/ADMIN_GUIDE.md
  docs/USER_GUIDE.md
  docs/USER_GUIDE_RU.md
Labels: documentation

#854 refactor(ci): refactor runners labels
  .github/workflows/dev_module_build-and-registration.yml
  .github/workflows/dev_module_build.yml
Labels: build/github/ubuntu

#860 fix(core): use v1beta1 version for ValidatingAdmissionPolicy
  hooks/migrate_delete_renamed_validation_admission_policy.py
Labels: bug
