Repository deckhouse/virtualization, pull requests merged in 2025-04, with the labels that each got.

#904 test: add regexp log parser
  tests/e2e/config/config.go
  tests/e2e/default_config.yaml
  tests/e2e/errlogger/errlogger.go
  tests/e2e/tests_suite_test.go
Labels: e2e/run

#903 feat(ci): add automatic e2e tests
  .github/scripts/js/ci.js
  .github/scripts/js/constants.js
  .github/scripts/js/e2e-commit-status.js
  .github/scripts/js/time.js
  .github/workflows/dev_module_build.yml
  tests/e2e/Taskfile.yaml
  tests/e2e/config/config.go
  tests/e2e/default_config.yaml
  tests/e2e/tests_suite_test.go
Labels: skip/e2e

#924 fix(ci): prevent pr info job from running on non-PR events
  .github/workflows/dev_module_build.yml
Labels: skip/e2e

#856 docs: fix external link on Installation page
  docs/INSTALL.md
  docs/INSTALL_RU.md
Labels: documentation

#885 chore(module): add module.yaml
  module.yaml
Labels: validation/skip/no_cyrillic

#926 fix(core): remove host-passthrough VMC
  images/hooks/cmd/005-prevent-default-vmclasses-deletion/main.go
  images/hooks/go.mod
  images/hooks/go.sum
  images/hooks/werf.inc.yaml
  templates/virtualization-controller/vmclasses-default.yaml
Labels: skip/e2e

#932 test: filter vm ip errors
  tests/e2e/default_config.yaml
Labels: skip/e2e

#940 chore(ci): set github runner to ubuntu-22.04 for validation ci
  .github/workflows/dev_validation.yaml
Labels: skip/e2e

#922 refactor(ci): workflows and base image, add build swtpm
  .github/workflows/dev_module_build.yml
  .helmignore
  .prettierignore
  .werf/defines/parse-base-images-map.tmpl
  .werf/images.yaml
  .werf/packages.yaml
  base-images/alt_image_versions.yml
  base-images/deckhouse_image_versions.yml
  base-images/deckhouse_images.yml
  base-images/virtualization_images.yml
  component_versions/README.md
  component_versions/version_map.yml
  images/base-alt-p10/werf.inc.yaml
  images/base-alt-p11-binaries/werf.inc.yaml
  images/base-alt-p11/werf.inc.yaml
  images/bounder/werf.inc.yaml
  images/cdi-artifact/werf.inc.yaml
  images/cdi-cloner/werf.inc.yaml
  images/distroless/werf.inc.yaml
  images/dvcr-artifact/werf.inc.yaml
  images/edk2/werf.inc.yaml
  images/hooks/werf.inc.yaml
  images/kube-api-rewriter/werf.inc.yaml
  images/libvirt/werf.inc.yaml
  images/packages/binaries/swtpm/werf.inc.yaml
  images/pre-delete-hook/werf.inc.yaml
  images/qemu/werf.inc.yaml
  images/virt-launcher/werf.inc.yaml
  images/virtualization-artifact/werf.inc.yaml
  images/vm-route-forge/werf.inc.yaml
  templates/kubevirt/kubevirt.yaml
  werf-giterminism.yaml
  werf.yaml
Labels: validation/skip/helm_templates

#942 chore(ci): add env SOURCE_REPO_GIT, change runners for release ci to self-hosted
  .github/workflows/dev_build_precache.yml
  .github/workflows/dev_module_build-and-registration.yml
  .github/workflows/release_module_build-and-registration.yml
  .github/workflows/release_module_release-channels.yml
Labels: skip/e2e

#927 chore(ci): add QoL-features to automatic e2e tests
  .github/workflows/dev_module_build.yml
  tests/e2e/Taskfile.yaml
Labels: skip/e2e

#944 chore(ci): add step helm setup
  .github/workflows/dev_validation.yaml
Labels: skip/e2e

#979 docs(vm): extend coreFraction description
  api/core/v1alpha2/virtual_machine.go
  crds/doc-ru-virtualmachines.yaml
  crds/virtualmachines.yaml
Labels: skip/e2e

#987 Backport: fix(vmip): fix double create VirtualMachineIPLease
  images/virtualization-artifact/pkg/controller/vmip/vmip_reconciler.go
  images/virtualization-artifact/pkg/controller/vmiplease/internal/lifecycle_handler.go
  images/virtualization-artifact/pkg/controller/vmiplease/internal/protection_handler.go
  images/virtualization-artifact/pkg/controller/vmiplease/internal/retention_handler.go
  images/virtualization-artifact/pkg/controller/vmiplease/vmiplease_reconciler.go
Labels: auto, backported

#986 fix(module): fix Kubernetes version detection in templates
  templates/admission-policy.yaml
  templates/virtualization-controller/validation-webhook.yaml
Labels: skip/e2e

#990 Backport: fix(module): fix Kubernetes version detection in templates
  templates/admission-policy.yaml
  templates/virtualization-controller/validation-webhook.yaml
Labels: auto, backported

#995 Backport: Changelog v0.17.0
  CHANGELOG/CHANGELOG-v0.17.0.yml
  CHANGELOG/CHANGELOG-v0.17.md
Labels: auto, backported

#998 Backport: chore(ci): fix Build Prod env escaping
  .github/workflows/release_module_release-channels.yml
Labels: auto, backported
