Repository deckhouse/virtualization, pull requests merged in 2025-06, with the labels that each got.

#1126 fix(vd): change brief for vd
  crds/virtualdisks.yaml
Labels: validation/skip/doc_changes

#1101 chore(ci): build lvm2
  component_versions/version_map.yml
  images/packages/binaries/lvm2/werf.inc.yaml
Labels: skip/e2e

#1131 chore(ci): add audit, dvcr, importer, uploader to svace
  images/dvcr-artifact/werf.inc.yaml
  images/dvcr/werf.inc.yaml
  images/virtualization-artifact/werf.inc.yaml
Labels: analyze/svace

#1135 Backport: fix(module): rework priority class templates after priority module deletion
  Chart.yaml
  Taskfile.yaml
  charts/deckhouse_lib_helm-1.55.1.tgz
  charts/deckhouse_lib_helm-1.7.0.tgz
  requirements.lock
  templates/cdi/config.yaml
  templates/kubevirt/kubevirt.yaml
Labels: auto, backported

#1143 Changelog v0.19.1
  CHANGELOG/CHANGELOG-v0.19.1.yml
  CHANGELOG/CHANGELOG-v0.19.md
Labels: changelog, auto, status/backport

#1144 Backport: Changelog v0.19.1
  CHANGELOG/CHANGELOG-v0.19.1.yml
  CHANGELOG/CHANGELOG-v0.19.md
Labels: auto, backported

#1145 chore (ci): Use Svace base image
  .werf/images.yaml
  base-images/deckhouse_images.yml
  images/dvcr-artifact/werf.inc.yaml
  images/dvcr/werf.inc.yaml
  images/libvirt/werf.inc.yaml
  images/qemu/werf.inc.yaml
  images/svace-builder/werf.inc.yaml
  images/virt-artifact/werf.inc.yaml
  images/virtualization-artifact/werf.inc.yaml
  images/vm-route-forge/werf.inc.yaml
  werf.yaml
Labels: analyze/svace

#1165 chore(vd): fix phase name for PVCLost phase
  api/core/v1alpha2/cluster_virtual_image.go
  api/core/v1alpha2/virtual_disk.go
  api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go
  crds/clustervirtualimages.yaml
  crds/virtualdisks.yaml
Labels: validation/skip/doc_changes

#1110 docs: update docs due v0.20.0
  docs/ADMIN_GUIDE.md
  docs/ADMIN_GUIDE.ru.md
  docs/INSTALL.md
  docs/INSTALL.ru.md
  docs/README.ru.md
  docs/USER_GUIDE.md
  docs/USER_GUIDE.ru.md
Labels: validation/skip/doc_changes

#1167 Backport: docs: update docs due v0.20.0
  docs/ADMIN_GUIDE.md
  docs/ADMIN_GUIDE.ru.md
  docs/INSTALL.md
  docs/INSTALL.ru.md
  docs/README.ru.md
  docs/USER_GUIDE.md
  docs/USER_GUIDE.ru.md
Labels: auto, backported

#1179 Backport: fix(module): patch spec.strategy for cdi-deployment
  templates/cdi/config.yaml
Labels: auto, backported

#1189 Backport: fix(core): fix discovery crd descheduler
  templates/descheduler/descheduler.yaml
  tools/kubeconform/fixtures/module-values.yaml
  tools/kubeconform/kubeconform.sh
Labels: auto, backported

#1177 fix(api): fix resource's names validation
  api/core/v1alpha2/cluster_virtual_image.go
  api/core/v1alpha2/virtual_disk.go
  api/core/v1alpha2/virtual_image.go
  crds/clustervirtualimages.yaml
  crds/virtualdisks.yaml
  crds/virtualimages.yaml
  crds/virtualmachines.yaml
  images/virtualization-artifact/pkg/common/validate/validate.go
  images/virtualization-artifact/pkg/controller/cvi/cvi_webhook.go
  images/virtualization-artifact/pkg/controller/vd/internal/validator/name_validator.go
  images/virtualization-artifact/pkg/controller/vi/vi_webhook.go
  images/virtualization-artifact/pkg/controller/vm/internal/validators/meta_validator.go
  tests/e2e/testdata/complex-test/cvi/cvi-from-cvi-ubuntu-http.yaml
  tests/e2e/testdata/complex-test/cvi/cvi-from-vi-ubuntu-http.yaml
  tests/e2e/testdata/connectivity/resources/vi.yaml
  tests/e2e/testdata/connectivity/resources/vm-connectivity-a.yaml
  tests/e2e/testdata/connectivity/resources/vm-connectivity-b.yaml
  tests/e2e/testdata/cvi/cvi_containerimage.yaml
  tests/e2e/testdata/images-creation/cvi/cvi_objectref_vi.yaml
  tests/e2e/testdata/images-creation/vi/vi_objectref_vi.yaml
  tests/e2e/testdata/images-creation/vi/vi_pvc_objectref_vi.yaml
Labels: validation/skip/doc_changes

#1191 Backport: fix(api): fix resource's names validation
  api/core/v1alpha2/cluster_virtual_image.go
  api/core/v1alpha2/virtual_disk.go
  api/core/v1alpha2/virtual_image.go
  crds/clustervirtualimages.yaml
  crds/virtualdisks.yaml
  crds/virtualimages.yaml
  crds/virtualmachines.yaml
  images/virtualization-artifact/pkg/common/validate/validate.go
  images/virtualization-artifact/pkg/controller/cvi/cvi_webhook.go
  images/virtualization-artifact/pkg/controller/vd/internal/validator/name_validator.go
  images/virtualization-artifact/pkg/controller/vi/vi_webhook.go
  images/virtualization-artifact/pkg/controller/vm/internal/validators/meta_validator.go
  tests/e2e/testdata/complex-test/cvi/cvi-from-cvi-ubuntu-http.yaml
  tests/e2e/testdata/complex-test/cvi/cvi-from-vi-ubuntu-http.yaml
  tests/e2e/testdata/connectivity/resources/vi.yaml
  tests/e2e/testdata/connectivity/resources/vm-connectivity-a.yaml
  tests/e2e/testdata/connectivity/resources/vm-connectivity-b.yaml
  tests/e2e/testdata/cvi/cvi_containerimage.yaml
  tests/e2e/testdata/images-creation/cvi/cvi_objectref_vi.yaml
  tests/e2e/testdata/images-creation/vi/vi_objectref_vi.yaml
  tests/e2e/testdata/images-creation/vi/vi_pvc_objectref_vi.yaml
Labels: auto, backported

#1195 Backport: fix(vm): nil pointer
  images/virtualization-artifact/pkg/controller/service/size_policy_service.go
  images/virtualization-artifact/pkg/controller/vmclass/internal/validators/sizing_policies_validator.go
Labels: auto, backported

#1196 Changelog v0.20.1
  CHANGELOG/CHANGELOG-v0.20.1.yml
  CHANGELOG/CHANGELOG-v0.20.md
Labels: changelog, auto, status/backport

#1200 Backport: docs: update docs due v0.21.0
  docs/ADMIN_GUIDE.md
  docs/ADMIN_GUIDE.ru.md
  docs/USER_GUIDE.md
  docs/USER_GUIDE.ru.md
Labels: auto, backported
