Repository deckhouse/virtualization, pull requests merged in 2025-09, with the labels that each got.

#1481 fix(docs): english documentation remove cyrillic characters cdi_kubevirt_patching
  docs/internal/cdi_kubevirt_patching.md
Labels: validation/skip/doc_changes

#1485 Backport: chore(module): fix install packages via dnf and yum
  templates/nodegroupconfiguration-selinux.yaml
Labels: auto, backported

#1487 Backport: chore(module): dedup lines on live migration memory graph
  monitoring/grafana-dashboards/main/virtual-machine.json
Labels: auto, backported

#1488 Backport: chore(module): add pre-created mount points to images
  .prettierignore
  .werf/defines/image-mountpoints.tmpl
  images/cdi-apiserver/mount-points.yaml
  images/cdi-apiserver/werf.inc.yaml
  images/cdi-cloner/mount-points.yaml
  images/cdi-cloner/werf.inc.yaml
  images/cdi-controller/mount-points.yaml
  images/cdi-controller/werf.inc.yaml
  images/cdi-importer/mount-points.yaml
  images/cdi-importer/werf.inc.yaml
  images/cdi-operator/mount-points.yaml
  images/cdi-operator/werf.inc.yaml
  images/distroless/werf.inc.yaml
  images/dvcr-importer/mount-points.yaml
  images/dvcr-importer/werf.inc.yaml
  images/dvcr-uploader/mount-points.yaml
  images/dvcr-uploader/werf.inc.yaml
  images/dvcr/mount-points.yaml
  images/dvcr/werf.inc.yaml
  images/kube-api-rewriter/mount-points.yaml
  images/kube-api-rewriter/werf.inc.yaml
  images/virt-api/mount-points.yaml
  images/virt-api/werf.inc.yaml
  images/virt-controller/mount-points.yaml
  images/virt-controller/werf.inc.yaml
  images/virt-handler/mount-points.yaml
  images/virt-handler/werf.inc.yaml
  images/virt-launcher/mount-points.yaml
  images/virt-launcher/werf.inc.yaml
  images/virt-operator/mount-points.yaml
  images/virt-operator/werf.inc.yaml
  images/virtualization-api/mount-points.yaml
  images/virtualization-api/werf.inc.yaml
  images/virtualization-artifact/pkg/common/consts.go
  images/virtualization-artifact/pkg/controller/importer/importer_pod.go
  images/virtualization-artifact/pkg/controller/importer/settings.go
  images/virtualization-artifact/pkg/controller/uploader/settings.go
  images/virtualization-artifact/pkg/controller/uploader/uploader_pod.go
  images/virtualization-audit/mount-points.yaml
  images/virtualization-audit/werf.inc.yaml
  images/virtualization-controller/mount-points.yaml
  images/virtualization-controller/werf.inc.yaml
  templates/virtualization-api/deployment.yaml
  tools/mounts/README.md
  tools/mounts/mountdir/.gitkeep
  tools/mounts/mountfile
Labels: backported
